---
version: '3.8'
services:
  frequi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    image: frequi
    # image: freqtradeorg/frequi:master
    restart: unless-stopped
    ports:
      - "8080:80"
